version: 0.2

phases:
  build:
    commands:
      - aws s3 cp LUIT-Gold-Sept-2023-CICD s3://luit-gold-september-2023-cicd-beta/ --acl public-read
      - if [ "$CODEBUILD_WEBHOOK_EVENT" == "PULL_REQUEST_MERGED" ] ;
      then aws s3 cp LUIT-Gold-Sept-2023-CICD s3://luit-gold-september-2023-cicd-prod/ --acl public-read ; fi
